Implement aws_rds_cluster resource
cloudskiff/driftctl pull request #1010
Opened 2021-09-03 12:48 UTC by sundowndev

| Q                 | A
| ----------------- | ---
| 🐛 Bug fix?       | no
| 🚀 New feature?   | yes
| ⚠ Deprecations?   | no
| ❌ BC Break       | no
| 🔗 Related issues | #947 
| ❓ Documentation  | yes 

## Description

Required permissions : 

- DescribeDBClusters 
- DescribeGlobalClusters

2021-09-13 13:28 UTC, wbeuil requested changes
Can you add a new test in `pkg/iac/terraform/state/terraform_state_reader_test.go` for this resource?

Why didn't you add an acceptance test?

2021-09-13 15:06 UTC, eliecharra reviewed
You should update the documentation (supported resources list, IAM minimal policy)

Keep in mind to update our acc test IAM policy if you add an acceptance test too.

2021-09-13 15:06 UTC, eliecharra commented on pkg/remote/aws/init.go
> +	remoteLibrary.AddDetailsFetcher(aws.AwsRDSClusterResourceType, common.NewGenericDetailsFetcher(aws.AwsRDSClusterResourceType, provider, deserializer))
Do we want to implement deep mode for future resources @cloudskiff/engineering

2021-09-16 09:09 UTC, eliecharra approved these changes

2021-09-16 09:18 UTC, merged