Implement aws_rds_cluster_instance resource
cloudskiff/driftctl pull request #1011
Opened 2021-09-03 14:28 UTC by sundowndev

| Q                 | A
| ----------------- | ---
| 🐛 Bug fix?       | no
| 🚀 New feature?   | yes
| ⚠ Deprecations?   | no
| ❌ BC Break       | no
| 🔗 Related issues | #954 
| ❓ Documentation  | yes 

## Description

This PR implements the aws_rds_cluster_instance resource. This resource exists in the AWS API as a `aws_db_instance`, that's the reason why it doesn't have an enumerator. I created a middleware to import remote db instances when they match a rds cluster instance from state.

2021-09-13 13:54 UTC, wbeuil requested changes
The way you're doing it in the middleware will not let us do a correct diff since you're just copying the remote one in both the state resources and in the remote resources.

We should instead map each rds_cluster_instance into rds_instance.

2021-09-14 14:04 UTC, sundowndev commented
> We should instead map each rds_cluster_instance into rds_instance.

@wbeuil not sure to understand what you mean exactly by "mapping into". How should we achieve that ?

2021-09-15 10:24 UTC, wbeuil commented
> > We should instead map each rds_cluster_instance into rds_instance.
> 
> @wbeuil not sure to understand what you mean exactly by "mapping into". How should we achieve that ?

Just like we do in other expander middleware like `AwsBucketPolicyExpander` or `AwsInstanceBlockDeviceResourceMapper` we want to add in the state resource list a new resource that you create from `AwsRDSClusterInstanceResourceType`. Otherwise in the case where we want to do a `deep-mode` scan it will never have drifts.

2021-09-28 14:42 UTC, moadibfr requested changes

2021-09-28 14:42 UTC, moadibfr commented on pkg/middlewares/aws_rds_cluster_instance_expander.go
> +				}).Debug("Created new db instance from RDS cluster instance")
I think you can break here when you found the corresponding id ?

2021-09-29 16:35 UTC, wbeuil submitted a review, later dismissed
LGTM

2021-09-30 12:27 UTC, merged