Add docs about middlewares
cloudskiff/driftctl pull request #1023
Opened 2021-09-08 14:36 UTC by sundowndev

| Q                 | A
| ----------------- | ---
| 🐛 Bug fix?       | no
| 🚀 New feature?   | no
| ⚠ Deprecations?   | no
| ❌ BC Break       | no
| 🔗 Related issues | Fix #950
| ❓ Documentation  | no 

## Description

This PR adds docs about middlewares: what middlewares does and how to create one.

2021-09-13 14:59 UTC, eliecharra submitted a review, later dismissed
I'm good with the content, maybe @wbeuil can do a wording review ?

2021-09-17 09:23 UTC, wbeuil requested changes

2021-09-17 09:23 UTC, wbeuil commented on docs/middlewares.md
> +Main goal of middleware is to make IaC and remote resources set to match. For this we filter some default resources, mutate or remove some fields in resources or even create and delete new resources.
`The main goal of middlewareS is to reconciliate IaC and remote resources. For this we filter default resources, mutate, or remove fields in resources ...`

2021-09-17 09:23 UTC, wbeuil commented on docs/middlewares.md
> +In the above example, we define a middleware called `AwsDefaultRoute` that will modify remote resources. Middleware can access two `*[]*resource.Resource` : the one from IaC side and the other one fr
`two *[]*resource.Resource: IaC resources first and then remote resources. The goal ...` (no space before : )
`these slices to ...`

2021-09-17 09:23 UTC, wbeuil commented on docs/middlewares.md
> +2) Filter noise from provider default resources
`Filter noiseS`

2021-09-17 09:23 UTC, wbeuil commented on docs/middlewares.md
> +4) `route53_records_id_reconcilier` that rework ID's to match terraform ones
`Terraform ones`

2021-09-20 08:14 UTC, wbeuil approved these changes

2021-09-20 08:14 UTC, merged