Add aws_appautoscaling_policy resource
cloudskiff/driftctl pull request #1028
Opened 2021-09-14 15:26 UTC by sundowndev

| Q                 | A
| ----------------- | ---
| 🐛 Bug fix?       | no
| 🚀 New feature?   | yes
| ⚠ Deprecations?   | no
| ❌ BC Break       | no
| 🔗 Related issues | #276
| ❓ Documentation  | yes 

## Description

Please include a summary of the change and which issue is fixed.
Please also include relevant motivation and context.

2021-09-28 14:57 UTC, moadibfr submitted a review, later dismissed

2021-10-01 10:23 UTC, wbeuil requested changes

2021-10-01 10:23 UTC, wbeuil commented on pkg/remote/aws/appautoscaling_policy_enumerator.go
> +	}
Same here than for the `scheduled_action`, let's do a single loop

2021-10-01 10:23 UTC, wbeuil commented on pkg/resource/aws/aws_appautoscaling_policy_test.go
> +					result.AssertDriftCountTotal(0)
No need for this line since it is implicit inside the `AssertInfrastructureIsInSync`

2021-10-01 10:23 UTC, wbeuil commented on pkg/resource/aws/aws_appautoscaling_policy_test.go
> +		Args:             []string{"scan", "--filter", "Type=='aws_appautoscaling_policy'"},
Use the `deep` flag

2021-10-01 10:23 UTC, wbeuil commented on pkg/resource/aws/aws_appautoscaling_policy.go
> +	resourceSchemaRepository.SetResolveReadAttributesFunc(AwsAppAutoscalingPolicyResourceType, func(res *resource.Resource) map[string]string {
Add the set flag function for the deep mode

2021-10-05 08:47 UTC, wbeuil approved these changes
LGTM

2021-10-05 09:10 UTC, merged