Add support for multiples IaC sources
cloudskiff/driftctl pull request #121
Opened 2021-01-15 11:46 UTC by eliecharra

| Q                 | A
| ----------------- | ---
| 🐛 Bug fix?       | no
| 🚀 New feature?   | yes
| ⚠ Deprecations?   | no
| ❌ BC Break       | no
| 🔗 Related issues | #50 
| ❓ Documentation  | yes

## Description

Support multiples `--from` flags as IaC source

2021-01-15 13:36 UTC, moadibfr requested changes

2021-01-15 13:36 UTC, moadibfr commented on pkg/remote/aws/test/route_table/.terraform.lock.hcl
> +# This file is maintained automatically by "terraform init".
is this file required ?

2021-01-15 13:42 UTC, eliecharra commented on pkg/remote/aws/test/route_table/.terraform.lock.hcl
> +# This file is maintained automatically by "terraform init".
Of course not nice catch, I removed it

2021-01-18 11:04 UTC, wbeuil commented on doc/cmd/scan/iac_source.md
> +ℹ️ Multiples states could be read by passing multiples flags `--from`
`Multiple states can be read by passing --from flags`

2021-01-18 16:16 UTC, wbeuil reviewed
Wonderful work !

2021-01-18 16:19 UTC, eliecharra commented on pkg/resource/chain_supplier.go
> +		runner: parallel.NewParallelRunner(context.TODO(), 3),
Hmm good question, I put 3 in a complete arbitrary way. Maybe we could set `runtime.NumCPU()` ?

2021-01-18 16:45 UTC, wbeuil commented on pkg/resource/chain_supplier.go
> +		runner: parallel.NewParallelRunner(context.TODO(), 3),
Maybe @moadibfr could help on this one

2021-01-18 16:49 UTC, eliecharra commented on pkg/resource/chain_supplier.go
> +		runner: parallel.NewParallelRunner(context.TODO(), 3),
As we are only doing I/O read and processing, I think it make sense to use every CPU thread for state parsing.

2021-01-18 16:55 UTC, wbeuil commented on pkg/resource/chain_supplier.go
> +		runner: parallel.NewParallelRunner(context.TODO(), 3),
Makes sense 👍🏻

2021-01-18 16:55 UTC, wbeuil submitted a review, later dismissed

2021-01-18 16:58 UTC, merged