Add aws_ebs_encryption_by_default
cloudskiff/driftctl pull request #1448
Opened 2022-03-28 13:09 UTC by sundowndev-snyk

| Q                 | A
| ----------------- | ---
| 🐛 Bug fix?       | no
| 🚀 New feature?   | yes
| ⚠ Deprecations?   | no
| ❌ BC Break       | no
| 🔗 Related issues | https://github.com/snyk/driftctl/issues/1383
| ❓ Documentation  | yes 

## Description

This PR add support for the `aws_ebs_encryption_by_default` resource.

**Please read [this comment](https://github.com/snyk/driftctl/issues/1383#issuecomment-1080441440) before reviewing.**

2022-03-30 15:34 UTC, wbeuil requested changes
Small comments and you miss this reply from Stephane I think

https://github.com/snyk/driftctl/issues/1383#issuecomment-1082014974

2022-03-30 15:34 UTC, wbeuil commented on pkg/middlewares/aws_ebs_encryption_by_default_reconciler_test.go
> +			"test encryption by default is managed",
Can you put the name of the args here so that it's easier to read the test.

2022-03-31 11:53 UTC, sundowndev-snyk commented on pkg/remote/aws/init.go
> +	remoteLibrary.AddEnumerator(NewLaunchTemplateEnumerator(ec2repository, factory))
Sorry for the noise here, It was just to group EC2 enumerators together

2022-03-31 12:00 UTC, sundowndev-snyk commented on pkg/remote/aws/init.go
> +	remoteLibrary.AddDetailsFetcher(aws.AwsEbsEncryptionByDefaultResourceType, common.NewGenericDetailsFetcher(aws.AwsEbsEncryptionByDefaultResourceType, provider, deserializer))
Good catch

2022-03-31 15:16 UTC, wbeuil requested changes
Small comments on the explanation of the middleware. Hope it's clearer, wdyt?

2022-03-31 15:16 UTC, wbeuil commented on pkg/middlewares/aws_ebs_encryption_by_default_reconciler.go
> +// Since we don't have an ID for remote resources of this type.
`AwsEbsEncryptionByDefaultReconciler is a middleware that either creates an 'aws_ebs_encryption_by_default' resource based on its equivalent state one just for the purpose of getting the Terraform custom Id, or removes the resource from our list of remote resources if it is not managed and is disabled.`

2022-04-01 08:57 UTC, wbeuil commented on pkg/remote/aws/init.go
> +	remoteLibrary.AddEnumerator(NewLaunchTemplateEnumerator(ec2repository, factory))
@sundowndev-snyk still this one last comment

2022-04-04 07:57 UTC, wbeuil approved these changes

2022-04-04 07:57 UTC, merged