skip warnings on commented out and empty lines
cloudskiff/driftctl pull request #178
Opened 2021-02-01 10:35 UTC by sfenman

| Q                 | A
| ----------------- | ---
| 🐛 Bug fix?       | no
| 🚀 New feature?   | no
| ⚠ Deprecations?   | no
| ❌ BC Break       | no
| 🔗 Related issues | #157
| ❓ Documentation  | no

## Description

Created a condition to skip empty or commented out (starting with # lines) from checking.

2021-02-01 10:43 UTC, eliecharra requested changes

2021-02-01 10:43 UTC, eliecharra commented on pkg/filter/driftignore.go
> +		if nbArgs == 0 || strings.HasPrefix(line, "#") {
`nbArgs == 0` is not exactly the check we want to ignore, we want to check if the line is empty

Your if directive should be moved just after `line := scanner.Text()`.
We do not want to call `readDriftIgnoreLine` for ignored lines.

You can also remove the `else` directive as you put a continue.

Something like below should do the job :

```diff
line := scanner.Text()
+if line == "" || strings.HasPrefix(line, "#") {
+  logrus.WithFields(logrus.Fields{
+    "line": line,
+  }).Debug("Skipped comment or empty line")
+  continue
+}
typeVal := readDriftIgnoreLine(line)
```

2021-02-01 10:45 UTC, eliecharra commented
Hi @sfenman thanks a lot for this PR 😃 , could you update the test suite to reflect your changes too ? 🙏🏻

2021-02-01 11:17 UTC, sfenman commented
Hi @eliecharra, thank you for the comments, I will update it shortly. I guess a new testing function is needed to test about empty and commented out lines explicitly right?

2021-02-01 11:22 UTC, eliecharra commented
> Hi @eliecharra, thank you for the comments, I will update it shortly. I guess a new testing function is needed to test about empty and commented out lines explicitly right?

I think you just have to update `drift_ignore_valid/.driftignore` by adding empty lines and comment.

We do not want to test that no warning are send at the moment at it will imply to use and inject a custom logger in driftignore logic to be able to mock it. So don't spend too much time on this 😃

2021-02-01 12:02 UTC, sfenman commented
I've made the changes based on your comments, but I couldn't omit the `else` directive because without it, the comments and the empty lines are still being passed to `readDriftIgnoreLine` .

2021-02-01 12:29 UTC, eliecharra commented
> I've made the changes based on your comments, but I couldn't omit the `else` directive because without it, the comments and the empty lines are still being passed to `readDriftIgnoreLine` .

You are missing the `continue` directive below in your `if` after the debug log, it will skip the line without the need for an else statement.

![image](https://user-images.githubusercontent.com/6154987/106458927-6572f400-6491-11eb-842e-a6b5b0d324ad.png)

It will make the code more readable and avoid unnecessary else nesting.

2021-02-01 12:39 UTC, eliecharra approved these changes
Awesome, thanks a lot for this fix @sfenman 🙏🏻

2021-02-01 12:43 UTC, merged

2021-02-03 16:20 UTC, wbeuil commented
@all-contributors please add @sfenman for code