add LIMITATIONS.md
cloudskiff/driftctl pull request #182
Opened 2021-02-02 09:43 UTC by sjourdan

| Q                 | A
| ----------------- | ---
| 🐛 Bug fix?       | no
| 🚀 New feature?   | no
| ⚠ Deprecations?   | no
| ❌ BC Break       | no
| 🔗 Related issues | #...
| ❓ Documentation  | yes 

## Description

We need a place to point our users to for known limitations., starting with the first we know about. 
It will keep getting better.

I placed it under `./doc` so it doesn't clutter the root of the repository and everything related to documentation is located at the same place.

2021-02-02 14:07 UTC, wbeuil commented on doc/LIMITATIONS.md
> +  - See the related [GitHub Discussion](https://github.com/cloudskiff/driftctl/discussions/130).
Can you remove the `.` inside the parentheses and aline the second `-`.

Thanks !

2021-02-02 14:25 UTC, eliecharra requested changes
Maybe we should add a precision, actually we can only scan one provider, so for a state using multiples aws provider with aliases we cannot scan every provider.

We can handle multiples states but only one `--to` flag so only one remote.

2021-02-02 14:25 UTC, eliecharra commented on doc/LIMITATIONS.md
> +- The user needs to use the same AWS region for both the scanned infrastructure and the S3 bucket where the Terraform state is stored (for example, a Terraform state stored on S3 on us-east-1 for an
`the same AWS region` and the same credentials too !

2021-02-02 18:06 UTC, eliecharra approved these changes
LGTM

2021-02-03 09:11 UTC, wbeuil approved these changes

2021-02-03 09:21 UTC, merged