Add github membership
cloudskiff/driftctl pull request #304
Opened 2021-02-26 15:14 UTC by eliecharra

| Q                 | A
| ----------------- | ---
| 🐛 Bug fix?       | no
| 🚀 New feature?   | yes
| ⚠ Deprecations?   | no
| ❌ BC Break       | no
| 🔗 Related issues | #247 
| ❓ Documentation  | yes

## Description

No acceptance for this one guys as I didn't find a simple way to accept invitation within acceptance test

2021-03-01 12:37 UTC, wbeuil requested changes
Small typo and wonder why you didn't make any acceptance tests ?

2021-03-01 13:16 UTC, eliecharra commented
> Small typo and wonder why you didn't make any acceptance tests ?

As I said in the PR description :

> No acceptance for this one guys as I didn't find a simple way to accept invitation within acceptance test

2021-03-01 13:19 UTC, wbeuil commented
Sorry forgot what you said in the description of the PR. Then just the small typo and I'm good with it

2021-03-01 14:05 UTC, eliecharra commented on pkg/resource/github/deserializer/github_membership_deserializer.go
> +			return nil, errors.Wrapf(err, "error when deserializing github_team %+v : %+v", raw, err)
Nice catch, fixed

2021-03-02 09:44 UTC, wbeuil approved these changes

2021-03-02 11:13 UTC, merged