Detect & exclude unsupported Terraform versions
cloudskiff/driftctl pull request #361
Opened 2021-03-23 14:53 UTC by sundowndev

| Q                 | A
| ----------------- | ---
| 🐛 Bug fix?       | yes
| 🚀 New feature?   | no
| ⚠ Deprecations?   | no
| ❌ BC Break       | no
| 🔗 Related issues | #340
| ❓ Documentation  | yes 

## Description

The goal of this patch is to warn the user about the state they provided in case it's from an unsupported version of Terraform.

> It is expected that running driftctl against a terraform state generated by an unsupported version should not be possible and be reported clearly to the user.
>
> In the case of multiple Terraform versions inside a set of tfstates, they should be ignored so at least some execution can happen. This is probably to combine with the future state exclusion feature.

## Implementation

I used [go-version](https://github.com/hashicorp/go-version) by hashicorp to perform the constraint check on Terraform version state. After parsing the state, the version is checked against the constraint (>= 0.11). If the constraint is satisfied, the scan can continue as usual. If it doesn't, a warning is displayed to tell the user this particular state was generated using an unsupported version of Terraform. The scan continue and the ignored state appears as drifted with 0% coverage.

```shell
$ driftctl scan --from tfstate://terraform1.tfstate 
WARN[0002] terraform1.tfstate: terraform state was generated using 0.9.8 which is currently not supported (constraints: >= 0.11)
Scanning resources: ⣟ (36)
Found unmanaged resources:
  aws_ebs_volume:
    - vol-01bd44304179ba354
    - vol-00fe1a5a8af4c6ef5
  aws_s3_bucket:
    - 09721498761983
    - 09721498761982
    - thisisatestbucket1298
    - thisisatestbucket1398
  aws_instance:
    - i-0ca7afc4ff96d6c4b
Found 7 resource(s)
 - 0% coverage
 - 0 covered by IaC
 - 7 not covered by IaC
 - 0 deleted on cloud provider
 - 0/0 drifted from IaC
exit status 1
```

## About constraints

I still need to figure out which version of Terraform is supported or not. But as stated in #340, we don't want to support versions below 0.11. So for now, the constraint is `>= 0.11`.

2021-03-29 08:30 UTC, moadibfr approved these changes

2021-04-12 12:01 UTC, wbeuil requested changes
Good work, I have 2 small comments

2021-04-12 12:01 UTC, wbeuil commented on pkg/iac/terraform/state/versions.go
> +		"Please read documentation at https://docs.driftctl.com/0.7.0/limitations", u.StateFile, u.Version)
We're gonna switch the link to the deep link one `https://docs.driftctl.com/limitations`

2021-04-12 12:16 UTC, sundowndev commented on pkg/iac/terraform/state/terraform_state_reader.go
> +)
I think it's just me, I'll revert this change

2021-04-12 16:23 UTC, wbeuil approved these changes
LGTM

2021-04-16 13:39 UTC, eliecharra commented
To rebase on `v0.8` and change target branch

2021-04-20 09:13 UTC, wbeuil approved these changes

2021-04-20 12:43 UTC, merged