Fix json output
cloudskiff/driftctl pull request #394
Opened 2021-03-30 15:44 UTC by eliecharra

| Q                 | A
| ----------------- | ---
| 🐛 Bug fix?       | yes
| 🚀 New feature?   | no
| ⚠ Deprecations?   | no
| ❌ BC Break       | no
| 🔗 Related issues | none
| ❓ Documentation  | none

## Description

Add truncate directive to remove file content when writing json output multiples times to the same file

2021-03-30 16:02 UTC, sundowndev commented on pkg/cmd/scan/output/testdata/output_multiples_times.json
> +		"total_deleted": 0,
total_missing

2021-03-30 16:02 UTC, sundowndev requested changes
Unit tests are not passing

2021-03-30 16:50 UTC, eliecharra commented
> Unit tests are not passing

Yeah I branched from main my bad 🤦🏻

2021-03-31 08:08 UTC, wbeuil approved these changes

2021-03-31 08:08 UTC, wbeuil commented
The problem of the linter here is `ERRO Running error: buildir: failed to load package : could not load export data: no export data for "github.com/google/go-cmp/cmp" `

2021-03-31 08:10 UTC, eliecharra commented
> The problem of the linter here is `ERRO Running error: buildir: failed to load package : could not load export data: no export data for "github.com/google/go-cmp/cmp" `

This is fixed by @sundowndev in main, it need to be fixed on branch `v0.7` too so I can rebase this branch

2021-03-31 10:08 UTC, sundowndev approved these changes

2021-03-31 10:08 UTC, merged