Fix aws_route53_record error when deserializing resource (null value is not allowed)
cloudskiff/driftctl pull request #401
Opened 2021-03-31 14:49 UTC by lotoussa

| Q                 | A
| ----------------- | ---
| 🐛 Bug fix?       | yes
| 🚀 New feature?   | no
| ⚠ Deprecations?   | no
| ❌ BC Break       | no
| 🔗 Related issues | #375 
| ❓ Documentation  | no

## Description

Everything is in the #375 ticket.
It's Draft cause i'm not able to reproduce the behaviour in the test part.

At least, the fix work in my env by fixing the records field of aws_route53_record with a pointer.

2021-03-31 16:24 UTC, eliecharra approved these changes
LGTM but be careful to keep your PR minimalist.

The typo fix in `pkg/middlewares/route53_records_test.go` is not related to this bug

2021-03-31 16:25 UTC, eliecharra commented
You need to rebase your PR onto branch `v0.7` to fix the linter issue in CI

2021-03-31 16:49 UTC, sundowndev approved these changes

2021-04-01 08:16 UTC, wbeuil requested changes

2021-04-01 08:16 UTC, wbeuil commented on pkg/resource/aws/aws_route53_record_ext.go
> +	// This ensure that if we find a nil value we dont drift
`This ensures that .... we don't drift`

2021-04-01 08:16 UTC, wbeuil commented on pkg/resource/aws/aws_route53_record_ext.go
> +	// This ensure that if we find a nil value we dont drift
`This ensures that .... we don't drift`

2021-04-01 08:16 UTC, wbeuil commented on pkg/resource/aws/aws_route53_record_ext.go
> +	// This ensure that if we find a nil value we dont drift
`This ensures that .... we don't drift`

2021-04-01 08:55 UTC, lotoussa commented on pkg/resource/aws/aws_route53_record_ext.go
> +	// This ensure that if we find a nil value we dont drift
done, thank you

2021-04-01 10:08 UTC, wbeuil requested changes
One last modification

2021-04-01 10:08 UTC, wbeuil commented on pkg/resource/aws/aws_route53_record_ext.go
> +	// This ensures that if we find a nil value we don't drift
`This ensures that if we find an empty records value we don't drift`

2021-04-01 12:20 UTC, merged