Publish driftctl to Arch user repository
cloudskiff/driftctl pull request #414
Opened 2021-04-08 15:34 UTC by eliecharra

| Q                 | A
| ----------------- | ---
| 🐛 Bug fix?       | no
| 🚀 New feature?   | no
| ⚠ Deprecations?   | no
| ❌ BC Break       | no
| 🔗 Related issues | #405 
| ❓ Documentation  | no

## Description

Add automatic publish to arch user repository.

2021-04-08 15:50 UTC, eliecharra commented
@wbeuil @moadibfr It was quite complicated, attentive review required there 🙏🏻

2021-04-09 11:01 UTC, wbeuil requested changes
LGTM as for the script and the ci config, I tested it with a clone repo. Too bad there is not an easier way though ... Just two small comments about the badges

2021-04-13 14:31 UTC, eliecharra commented on README.md
> +  <img src="https://img.shields.io/github/v/release/cloudskiff/driftctl?label=latest%20version">
Yeah I think it was unclear with the new block label, will revert this with the usage of individual labels

2021-04-13 14:34 UTC, eliecharra commented on README.md
> +  </a>
And what about something like this ?

<details>
  <summary>Packages</summary>
    <a href="https://repology.org/project/driftctl/versions">
    <img src="https://repology.org/badge/vertical-allrepos/driftctl.svg" alt="Packaging status">
  </a>
</details>

2021-04-13 15:27 UTC, wbeuil commented on README.md
> +  </a>
Didn't know we could do that in markdown ! I'm ok with that

2021-04-14 08:56 UTC, wbeuil approved these changes

2021-04-14 12:19 UTC, merged