migrate some more resource to new resource handling
cloudskiff/driftctl pull request #478
Opened 2021-04-30 17:36 UTC by moadibfr

| Q                 | A
| ----------------- | ---
| 🐛 Bug fix?       | no
| 🚀 New feature?   | no
| ⚠ Deprecations?   | yes
| ❌ BC Break       | yes
| 🔗 Related issues | #347
| ❓ Documentation  | no

## Description

migrate sqs-queue
migrate sqs_queue_policy and sqs_default_queue_policy
migrate subnet and default subnet
 migrate vpc

2021-05-10 09:11 UTC, eliecharra reviewed
Some small remarks

2021-05-11 10:10 UTC, moadibfr commented on pkg/middlewares/aws_sqs_queue_policy_expander_test.go
> +					return input["id"] == "foo"
no there is only one resource in this test I think you are misreading resourcesFromState and expected?

2021-05-11 12:55 UTC, eliecharra commented on pkg/middlewares/aws_sqs_queue_policy_expander_test.go
> +					return input["id"] == "foo"
Yeah I inverted with expected my bad

2021-05-12 08:15 UTC, moadibfr commented on pkg/middlewares/aws_sqs_queue_policy_expander_test.go
> +				factory.On("CreateResource", mock.Anything, "aws_sqs_queue_policy").Once().Return(nil, nil)
seems like I missed one...

2021-05-17 14:40 UTC, wbeuil requested changes

2021-05-17 14:40 UTC, wbeuil commented on pkg/resource/aws/aws_sqs_queue_policy.go
> +	})
Where is the normalization of the json string that we did on the `_ext` file ?

```go
resourceSchemaRepository.SetNormalizeFunc(AwsSqsQueuePolicyResourceType, func(val *resource.Attributes) {
  jsonString, err := helpers.NormalizeJsonString((*val)["policy"])
  if err != nil {
    return
  }
  val.SafeSet([]string{"policy"}, jsonString)
})
```

2021-05-17 14:40 UTC, wbeuil commented on pkg/resource/aws/aws_vpc_test.go
> +		Paths: []string{"./testdata/acc/aws_vpc"},
It misses the `TerraformVersion: "X.X.X"` arg in the `AccTestCase`

2021-05-17 14:40 UTC, wbeuil commented on pkg/resource/aws/metadatas.go
> +	initAwsDefaultSubnetMetaData(resourceSchemaRepository)
This is a duplicate of the one line 11.

2021-05-17 14:40 UTC, wbeuil commented on pkg/resource/resource.go
> +	"aws_default_subnet",
Please remove one `aws_subnet` and there is already the `aws_default_subnet` line 28

2021-05-18 08:32 UTC, wbeuil approved these changes

2021-05-18 08:46 UTC, eliecharra approved these changes

2021-05-18 08:54 UTC, merged