Create driftignore generator command
cloudskiff/driftctl pull request #501
Opened 2021-05-10 09:05 UTC by sundowndev

| Q                 | A
| ----------------- | ---
| 🐛 Bug fix?       | no
| 🚀 New feature?   | yes
| ⚠ Deprecations?   | no
| ❌ BC Break       | no
| 🔗 Related issues | #415
| ❓ Documentation  | yes 

**NOTICE: this is a backport of #433 into v0.9.0. This feature was removed of v0.8.0 because of UX issues.**

TL;DR: The purpose of this change is to be able to generate a .driftignore file containing current drifts.

## Context

New users can struggle when trying the tool because the output is too large and hard to read. They might want to ignore all the current drifts so they can start introduce the tool in their workflow quickly and fix the current issues later. This feature allows them to create a driftignore file from a JSON output.

## Flags

- `--exclude-unmanaged` allows to control whether unmanaged resources are included or not
- `--exclude-missing` allows to control whether missing resources are included or not
- `--exclude-changed` allows to control whether changed resources are included or not

## Examples

```shell
# Ignore all current drifts
$ driftctl scan -o json://stdout | driftctl gen-driftignore -f /dev/stdin > .driftignore

# Changed resources will not be included
$ driftctl scan --from tfstate://state1.tfstate -o json://stdout | driftctl gen-driftignore --exclude-changed

# Unmanaged resources will not be included
$ cat result.json | driftctl gen-driftignore --exclude-unmanaged
```

2021-05-17 17:03 UTC, sjourdan requested changes
I still have the same usability issue mentioned in [this comment](https://github.com/cloudskiff/driftctl/issues/415#issuecomment-834607192): 

A user running the general help command will be encouraged to run `gen-driftignore`, but nothing will happen if the user actually executes it: 

```shell
~/bin/driftctl-0.9.0 --help
Detect, track and alert on infrastructure drift.

Usage: driftctl <command> [flags]

COMMANDS:
  completion               Generate completion script
  gen-driftignore          Generate a .driftignore file based on your scan result
  scan                     Scan
  version                  Display driftctl version

[...]

❯  ~/bin/driftctl-0.9.0 gen-driftignore 

```

Sure, if the user runs twice `--help`, he will get the right information in the output (`driftctl scan -o json://stdout | driftctl gen-driftignore > .driftignore`), but that's 3 steps to an actual result instead of 1 - for a feature meant to ease a user's journey it's too much. 

A first step could be to show the user how to use the command if used directly, as mentioned in the original comment: 

```shell 
❯  driftctl-0.9.0 gen-driftignore
ERROR: this command is not meant to be used directly, please read the documentation at docs.driftctl.com/yaddiyadda
```

Or also just reuse the wording you already included in the second level help: 

```shell 
❯  driftctl-0.9.0 gen-driftignore
ERROR: this command is not meant to be used directly, please read the documentation at docs.driftctl.com/yaddiyadda

Example: driftctl scan -o json://stdout | driftctl gen-driftignore > .driftignore
```

Docker usage won't be exactly easy for a first time user too: 

```
$ docker run -it --rm \
  -v ~/.aws:/root/.aws:ro \
  -v $(pwd):/app:ro \
  -v ~/.driftctl:/root/.driftctl \
  -e AWS_PROFILE=testing \
  -e AWS_REGION=us-east-1 \
  driftctl:dev scan -o json://stdout | \
  docker run -i --rm \
  driftctl:dev gen-driftignore 2>&1 > .driftignore
# Resources not covered by IaC
[...]
```

How would you use the feature?

2021-05-18 14:16 UTC, sjourdan approved these changes

2021-05-24 11:03 UTC, wbeuil requested changes

2021-05-24 11:03 UTC, wbeuil commented on pkg/cmd/scan.go
> +	}
Wonder if we should put this `Println` in the `!analysis.IsSync()` if statement just below.

2021-05-24 11:41 UTC, sundowndev commented on pkg/cmd/gen_driftignore.go
> +		Long:  "This command will generate a new .driftignore file containing your current drifts and send output to /dev/stdout\n\nExample: driftctl scan -o json://stdout | driftctl gen-driftignore > .dri
You need to specify option `-i` : `-i /dev/stdin`

2021-05-24 11:44 UTC, wbeuil commented on pkg/cmd/gen_driftignore.go
> +		Long:  "This command will generate a new .driftignore file containing your current drifts and send output to /dev/stdout\n\nExample: driftctl scan -o json://stdout | driftctl gen-driftignore > .dri
This is the new error I've got:

```
DEBU[0003] Starting middleware middleware=middlewares.AwsNatGatewayEipAssoc
DEBU[0003] Starting middleware middleware=middlewares.AwsBucketPolicyExpander
DEBU[0003] Starting middleware middleware=middlewares.AwsSqsQueuePolicyExpander
DEBU[0003] Starting middleware middleware=middlewares.AwsDefaultSqsQueuePolicy
DEBU[0003] Starting middleware middleware=middlewares.AwsSNSTopicPolicyExpander
DEBU[0003] Starting middleware middleware=middlewares.AwsDefaults
DEBU[0003] Ignoring default AWS resource id=AWSServiceRoleForVPCTransitGateway type=aws_iam_role
DEBU[0003] Ignoring default AWS resource id=AWSServiceRoleForRDS type=aws_iam_role
DEBU[0003] Ignoring default AWS resource id=AWSServiceRoleForSSO type=aws_iam_role
DEBU[0003] Ignoring default AWS resource id=AWSServiceRoleForECS type=aws_iam_role
DEBU[0003] Checking for driftignore
DEBU[0003] Closing providers
DEBU[0003] Closing provider key=aws
DEBU[0003] Closing gRPC client alias=eu-west-3
invalid character 'H' after top-level value
```

2021-05-24 12:29 UTC, sundowndev commented on pkg/cmd/scan.go
> +	}
Yep, makes sens, I'll do that

2021-05-24 12:35 UTC, sundowndev commented on pkg/cmd/gen_driftignore.go
> +		Long:  "This command will generate a new .driftignore file containing your current drifts and send output to /dev/stdout\n\nExample: driftctl scan -o json://stdout | driftctl gen-driftignore > .dri
Should be fixed now

2021-05-24 12:58 UTC, moadibfr requested changes

2021-05-24 12:58 UTC, moadibfr commented on test.html
> +<html>
is this suppose to be here ?

2021-05-24 13:00 UTC, moadibfr approved these changes

2021-05-24 13:20 UTC, wbeuil approved these changes
LGTM ! Well done

2021-05-24 13:21 UTC, merged