suppliers dependency
cloudskiff/driftctl pull request #566
Opened 2021-05-28 15:47 UTC by lotoussa

| Q                 | A
| ----------------- | ---
| 🐛 Bug fix?       | no
| 🚀 New feature?   | no
| ⚠ Deprecations?   | no
| ❌ BC Break       | no
| 🔗 Related issues | #165 
| ❓ Documentation  | no

## Description

Each supplier must be totally independent and do not call other provider methods.

For caching purpose we may want to wrap the aws client in our own struct.

Merge of every PR of the ticket.

2021-06-01 14:26 UTC, wbeuil approved these changes
LGTM, do not merge it for now.

2021-06-07 12:35 UTC, wbeuil requested changes

2021-06-07 12:35 UTC, wbeuil commented on pkg/remote/aws/iam_policy_supplier_test.go
> +	mocks2 "github.com/cloudskiff/driftctl/test/mocks"
Should be `mocks`

2021-06-07 12:35 UTC, wbeuil commented on pkg/remote/aws/iam_role_policy_attachment_supplier_test.go
> +	mocks2 "github.com/cloudskiff/driftctl/test/mocks"
`mocks`

2021-06-07 12:35 UTC, wbeuil commented on pkg/remote/aws/iam_role_supplier_test.go
> +	mocks2 "github.com/cloudskiff/driftctl/test/mocks"
`mocks`

2021-06-07 12:35 UTC, wbeuil commented on pkg/remote/aws/internet_gateway_supplier.go
> +	client       repository.EC2Repository
Let's rewrite each `client` to `repo`.

2021-06-07 12:35 UTC, wbeuil commented on pkg/remote/aws/nat_gateway_supplier.go
> +	client       repository.EC2Repository
`repo`

2021-06-07 12:35 UTC, wbeuil commented on pkg/remote/aws/route_supplier.go
> +	client       repository.EC2Repository
`repo`

2021-06-07 12:35 UTC, wbeuil commented on pkg/remote/aws/route_table_association_supplier.go
> +	client       repository.EC2Repository
`repo`

2021-06-07 12:35 UTC, wbeuil commented on pkg/remote/aws/route_table_supplier.go
> +	client                  repository.EC2Repository
`repo`

2021-06-07 12:35 UTC, wbeuil commented on pkg/remote/aws/subnet_supplier.go
> +	client              repository.EC2Repository
`repo`

2021-06-07 12:35 UTC, wbeuil commented on pkg/remote/aws/vpc_security_group_rule_supplier.go
> +	client       repository.EC2Repository
`repo`

2021-06-07 12:35 UTC, wbeuil commented on pkg/remote/aws/vpc_security_group_supplier.go
> +	client                     repository.EC2Repository
`repo`

2021-06-07 12:35 UTC, wbeuil commented on pkg/remote/aws/vpc_supplier.go
> +	client           repository.EC2Repository
`repo`

2021-06-07 12:35 UTC, wbeuil commented on pkg/remote/aws/init.go
>  	supplierLibrary.AddSupplier(NewIamUserSupplier(provider, deserializer))
Just like what you did for `ec2repo`, can you add `iamrepo` as an argument to each IAM supplier here.

2021-06-07 12:43 UTC, sundowndev requested changes

2021-06-07 12:43 UTC, sundowndev commented on pkg/remote/aws/repository/ec2_repository.go
> +	ListAllSecurityGroups() ([]*ec2.SecurityGroup, []*ec2.SecurityGroup, error)
Can you add cache for those methods?

2021-06-07 15:35 UTC, sundowndev approved these changes

2021-06-07 16:03 UTC, wbeuil approved these changes

2021-06-08 08:26 UTC, merged