Add driftignore flag to specify a different .driftignore file
cloudskiff/driftctl pull request #660
Opened 2021-06-17 13:40 UTC by sundowndev

| Q                 | A
| ----------------- | ---
| 🐛 Bug fix?       | no
| 🚀 New feature?   | yes
| ⚠ Deprecations?   | no
| ❌ BC Break       | no
| 🔗 Related issues | #618
| ❓ Documentation  | yes 

## Description

This PR adds a new driftignore flag to allow user to specify a different filename than .driftignore.

2021-06-17 13:43 UTC, lotoussa approved these changes

2021-06-18 08:28 UTC, eliecharra requested changes
One small remark to fix, otherwise good work 🎉

2021-06-18 08:28 UTC, eliecharra commented on pkg/filter/driftignore.go
> +		DriftignorePath:          path,
This should be unexported

2021-06-21 12:55 UTC, wbeuil approved these changes

2021-06-21 13:06 UTC, eliecharra approved these changes

2021-06-21 13:13 UTC, merged