Handle managed_policy_arns in aws_iam_roles
cloudskiff/driftctl pull request #663
Opened 2021-06-17 15:26 UTC by eliecharra

| Q                 | A
| ----------------- | ---
| 🐛 Bug fix?       | yes
| 🚀 New feature?   | no
| ⚠ Deprecations?   | no
| ❌ BC Break       | no
| 🔗 Related issues | #627
| ❓ Documentation  | no

2021-06-17 15:29 UTC, lotoussa submitted a review, later dismissed
ok i see how you do it, cool
lgtm

2021-06-18 10:07 UTC, lotoussa approved these changes

2021-06-21 11:09 UTC, wbeuil requested changes
Small changes

2021-06-21 11:53 UTC, eliecharra commented on pkg/resource/aws/aws_iam_role_test.go
> +					result.AssertManagedCount(1)
Here I do not want to catch unmanaged resources (they persist dangling role to allow access to driftctl in QA pipeline)

2021-06-21 11:54 UTC, wbeuil commented on pkg/resource/aws/aws_iam_role_test.go
> +					result.AssertManagedCount(1)
Ok got it !

2021-06-21 11:55 UTC, wbeuil approved these changes

2021-06-21 12:16 UTC, merged