prevent context access to mark pr ci as failed
cloudskiff/driftctl pull request #668
Opened 2021-06-21 14:18 UTC by moadibfr

| Q                 | A
| ----------------- | ---
| 🐛 Bug fix?       | yes
| 🚀 New feature?   | no
| ⚠ Deprecations?   |no
| ❌ BC Break       | no
| 🔗 Related issues | 
| ❓ Documentation  | no 

## Description
prevent context access to mark pr ci as failed

2021-06-21 15:52 UTC, lotoussa submitted a review, later dismissed

2021-06-21 15:57 UTC, sundowndev approved these changes

2021-06-22 14:24 UTC, eliecharra requested changes
You can remove

```yaml
      force_acc_test:
        type: boolean
        default: false
```

2021-06-23 09:08 UTC, eliecharra approved these changes
Very nice 👍🏻

2021-06-23 09:08 UTC, merged