Split ec2_key_pair_supplier
cloudskiff/driftctl pull request #763
Opened 2021-06-29 15:25 UTC by wbeuil

Fix #721

2021-06-29 15:28 UTC, lotoussa approved these changes

2021-06-30 08:34 UTC, sundowndev approved these changes

2021-06-30 15:34 UTC, eliecharra requested changes

2021-06-30 15:34 UTC, eliecharra commented on pkg/remote/aws/ec2_key_pair_detail_fetcher.go
> +type EC2KeyPairDetailsFetcher struct {
You can use `GenericDetailFetcher`

2021-07-02 13:00 UTC, moadibfr approved these changes

2021-07-02 14:43 UTC, moadibfr approved these changes

2021-07-02 14:58 UTC, merged