Split route53_zone_supplier
cloudskiff/driftctl pull request #765
Opened 2021-06-30 09:05 UTC by sundowndev

Fixes #738

2021-07-02 13:05 UTC, moadibfr requested changes

2021-07-02 13:05 UTC, moadibfr commented on pkg/remote/aws/route53_health_check_detail_fetcher.go
> +		Attributes: map[string]string{},
think you don't need an empty map here

2021-07-02 13:05 UTC, moadibfr commented on pkg/remote/aws/route53_health_check_detail_fetcher.go
> +		Attributes: map[string]string{},
so you could use the common.GenericDetailsFetcher

2021-07-05 15:36 UTC, eliecharra requested changes

2021-07-05 15:36 UTC, eliecharra commented on pkg/remote/aws/route53_zone_enumerator.go
> +func cleanZoneID(ID string) string {
Is this method used in another place in this pkg ? If not I think it can be removed

2021-07-05 15:45 UTC, eliecharra approved these changes

2021-07-05 16:08 UTC, moadibfr approved these changes

2021-07-05 16:10 UTC, merged