Split vpc_supplier
cloudskiff/driftctl pull request #769
Opened 2021-06-30 16:01 UTC by sundowndev

Fixes #754

2021-07-01 08:33 UTC, eliecharra requested changes
LGTM, but you can remove `pkg/remote/test/vpc/schema.golden.json` schema files because now we are using a new logic to avoid to duplicate shemas. They are now in `test/terraform/schemas`

2021-07-01 09:34 UTC, eliecharra requested changes
You should revert changes on `test/terraform/schemas/aws/3.19.0.json`

2021-07-01 13:26 UTC, eliecharra submitted a review, later dismissed

2021-07-02 13:06 UTC, moadibfr submitted a review, later dismissed

2021-07-05 08:37 UTC, eliecharra submitted a review, later dismissed

2021-07-05 09:43 UTC, eliecharra approved these changes

2021-07-05 09:43 UTC, merged