split Github team membership supplier
cloudskiff/driftctl pull request #777
Opened 2021-07-01 10:34 UTC by moadibfr

| Q                 | A
| ----------------- | ---
| 🐛 Bug fix?       | no
| 🚀 New feature?   | yes
| ⚠ Deprecations?   | no
| ❌ BC Break       | no
| 🔗 Related issues | #758  
| ❓ Documentation  | no 

## Description
split github team membership supplier

2021-07-02 16:02 UTC, wbeuil submitted a review, later dismissed

2021-07-05 08:18 UTC, eliecharra requested changes

2021-07-05 08:18 UTC, eliecharra commented on pkg/remote/github/init.go
> -	supplierLibrary.AddSupplier(NewGithubMembershipSupplier(provider, repository, deserializer))
The Membership supplier should not be removed here as we only handle team membership in this PR

2021-07-05 13:37 UTC, eliecharra approved these changes

2021-07-05 13:45 UTC, merged