Split iam role policy supplier
cloudskiff/driftctl pull request #836
Opened 2021-07-12 10:27 UTC by sundowndev

fixes #725

2021-07-12 14:09 UTC, eliecharra requested changes
schemas files need to be removed

2021-07-12 17:10 UTC, lotoussa submitted a review, later dismissed

2021-07-13 13:12 UTC, eliecharra approved these changes

2021-07-13 13:13 UTC, eliecharra commented
@sundowndev Need to be rebased

2021-07-13 13:24 UTC, eliecharra approved these changes

2021-07-13 13:24 UTC, merged