update documentation for contributors to be able to add new resources
cloudskiff/driftctl pull request #904
Opened 2021-08-02 15:09 UTC by moadibfr

| Q                 | A
| ----------------- | ---
| 🐛 Bug fix?       | no
| 🚀 New feature?   | no
| ⚠ Deprecations?   | no
| ❌ BC Break       | no
| 🔗 Related issues | #867
| ❓ Documentation  | yes 

## Description
update documentation for contributors to be able to add new resources

2021-08-10 13:56 UTC, eliecharra commented
@wbeuil I added some fixes, when you'll get back from holidays this one need your legendary doc review pass 🙏🏻

2021-08-24 13:45 UTC, wbeuil requested changes
The first batch of comments. Once updated, I will do another review.

2021-08-24 13:45 UTC, wbeuil commented on docs/new-resource.md
> +This is used to build a resources list. Enumerators can be found in `pkg/remote/<providername>/<type>_enumerator.go`. It will call the cloud provider SDK to get the list of resources.
Remove the first sentence

2021-08-24 13:45 UTC, wbeuil commented on docs/new-resource.md
> +Most of the resource returned by enumerator have empty attributes: they only represent type and terraform id.
`Note that at this point, resources should not be entirely fetched and most of them will have empty attributes (e.g. only their id and type)`

2021-08-24 13:45 UTC, wbeuil commented on docs/new-resource.md
> +**There are exception to this**:
`exceptions`

2021-08-24 13:45 UTC, wbeuil commented on docs/new-resource.md
> +- Sometime, you will need some more information about resources to retrieve them using the provider they should be added to the resource attribute maps.
`Sometimes, you will need more information about resources for them to be fully fetched in the DetailsFetcher. For those cases, you will add specific attributes to the map of data.`

2021-08-24 13:45 UTC, wbeuil commented on docs/new-resource.md
> +You will probably need to at least add a listing function to list you new resource.
I find it useless. You can remove this sentence.

2021-08-24 13:45 UTC, wbeuil commented on docs/new-resource.md
> +You should use an already implemented Enumerator as example.
`You can use an ...`

2021-08-24 13:45 UTC, wbeuil commented on docs/new-resource.md
> +Note that we use the classic repository to hide calls to the provider sdk.
I find it useless. You can remove this sentence.

2021-08-24 13:45 UTC, wbeuil commented on docs/new-resource.md
> +these informations should be fetched manually by the enumerator using the remote sdk.
`For complex cases (e.g. middlewares) where you would need driftctl to run as expected in deep and non-deep mode, you would need to enumerate resources as well as to fetch manually specific attributes, using the remote SDK, before adding them to the map of data.`

2021-08-24 13:45 UTC, wbeuil commented on docs/new-resource.md
> +For example when implementing ec2_instance resource you will need to add a ListAllInstances() function to `repository.EC2Repository`.
`For example, to implement ec2_instance (with backticks) ... `

2021-08-24 13:45 UTC, wbeuil commented on docs/new-resource.md
> +For example when implementing ec2_instance resource you will need to add a ListAllInstances() function to `repository.EC2Repository`.
Newline

2021-08-24 13:45 UTC, wbeuil commented on docs/new-resource.md
> +It will be called by the enumerator to retrieve the instances list.
`Bear in mind it will be called by the Enumerator ... the list of instances.`

2021-08-24 13:45 UTC, wbeuil commented on docs/new-resource.md
> +- an instance of `Repository` that you will use to retrieved information about the resource
`use to retrieve information ...`

2021-08-24 13:45 UTC, wbeuil commented on docs/new-resource.md
> +Enumerator then need to implement:
`needs to`

2021-08-24 13:45 UTC, wbeuil commented on docs/new-resource.md
> +- `SupportedType() resource.ResourceType` that will return the constant you defined in the type file at first step
Remove `at first step`

2021-08-24 13:45 UTC, wbeuil commented on docs/new-resource.md
> +- `Enumerate() ([]*resource.Resource, error)` that will return the resource listing.
Remove the point at the end and change it to `that will return the list of resources`

2021-08-24 14:37 UTC, wbeuil commented on docs/new-remote-provider.md
> +`+tf` mean that we use terraform to retrieve details of resources, in the future maybe it will exist other way to read resource details.
@eliecharra `to retrieve resources' details`

2021-08-24 14:40 UTC, wbeuil commented on docs/new-resource.md
> +And here you'll see a more detailed flow of the retrieving resource sequence from remote:
@eliecharra `and the fetching of resources' details from the remote:`

2021-08-25 10:35 UTC, wbeuil requested changes

2021-08-25 10:35 UTC, wbeuil commented on docs/new-resource.md
> +So as you can see this contains the logic to create the GitHub client (it might be created outside the repository if it makes sense to share it between multiple repositories).
`As you can see,  ...`

2021-08-25 10:35 UTC, wbeuil commented on docs/new-resource.md
> +Most of the resource returned by enumerator have empty attributes: they only represent type and terraform id.
Forgot to tell you to remove the second sentence that starts with `Most of the resource ...`

2021-08-25 10:35 UTC, wbeuil commented on docs/new-resource.md
> +- Sometimes, you will need more information about resources for them to be fetched in the `DetailFetcher`. For those cases, you will add specific attributes to the map of data.
`DetailSFetcher`

2021-08-25 10:35 UTC, wbeuil commented on docs/new-resource.md
> +You will probably need to at least add a listing function to list you new resource.
I'm not finding this sentence relevant to keep. Let's remove it.

2021-08-25 10:35 UTC, wbeuil commented on docs/new-resource.md
> +As you can see, listing error are treated in a particular way. Instead of failing and stopping the scan they will be handled, and an alert will be created.
`listing errorS ...`

2021-08-25 10:35 UTC, wbeuil commented on docs/new-resource.md
> +You should test enumerator behavior when you do not have permission to enumerate resource, in the snippet above, `ListAllInstances` may return an `AccessDenied` error or so that should be handled.
`... to enumerate resourceS. In the snippet above, ListAllInstances may return an AccessDenied error that should be handled.`

2021-08-25 10:35 UTC, wbeuil commented on docs/new-resource.md
> +Once the enumerator is written you have to add it to the remote init located in `pkg/remote/<providername>/init.go` :
`to the remote initialization located in pkg/remote/<providername>/init.go:`
Newline

2021-08-25 10:35 UTC, wbeuil commented on docs/new-resource.md
> +DetailsFetcher are only used by driftctl experimental deep mode.
`DetailsFetcherS are ...`

2021-08-25 10:35 UTC, wbeuil commented on docs/new-resource.md
> +This is the component that call terraform provider to retrieve the full attribute for each resource.
`Terraform provider to retrieve all attributes for each resource.`

2021-08-25 10:35 UTC, wbeuil commented on docs/new-resource.md
> +We do not want to reimplement what has already been done in every terraform provider, so you should not call the remote sdk there.
`... in each Terraform provider. Thus, you should not call the remote SDK there.`

2021-08-25 10:35 UTC, wbeuil commented on docs/new-resource.md
> +If `common.GenericDetailsFetcher` satisfy your needs you should always prefer using it instead of implementing a custom `DetailsFetcher` in a new struct.
`satisfies your needs ...`

2021-08-25 10:35 UTC, wbeuil commented on docs/new-resource.md
> +The `DetailsFetcher` should also be added to `pkg/remote/<providername>/init.go` even if you use the generic version :
`the generic version:`
Newline

2021-08-25 10:35 UTC, wbeuil commented on docs/new-resource.md
> +
Remove one newline

2021-08-25 10:35 UTC, wbeuil commented on docs/new-resource.md
> +You can find example of "functional" tests in pkg/remote/<type>_scanner_test.go
Backticks around the file and the `.` at the end of the sentence.

2021-08-25 10:35 UTC, wbeuil commented on docs/new-resource.md
> +You can find example of "functional" tests in pkg/remote/<type>_scanner_test.go
I would rather put emphasis with bold text for **functional tests** rather than simple "

2021-08-25 10:35 UTC, wbeuil commented on docs/new-resource.md
> +You should also add acceptance tests if you think it makes sense, they are located next to the resource definition described at first step.
`add **acceptance tests** ... makes sense. They are located ... in the first step.`

2021-08-25 10:35 UTC, wbeuil commented on docs/new-resource.md
> +More information about test can be found in [testing documentation](testing.md)
`about adding tests`

2021-08-25 11:39 UTC, eliecharra commented on docs/new-resource.md
> +- `remote.comon.DetailsFetcher` is used to enumerate resources. It makes a call to Terraform provider `ReadResource`.
Oops nice catch my brain was probable already gone at this stage 😅

2021-08-25 12:56 UTC, wbeuil approved these changes
GO !

2021-08-25 13:04 UTC, merged